name: Security

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Scan for vulnerabilities in go code
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true